# Generated by Django 6.0.3 on 2026-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('url', 'URL')], default='text', max_length=10)),
                ('summary_length', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('detailed', 'Detailed')], default='medium', max_length=10)),
                ('original_text', models.TextField()),
                ('generated_summary', models.TextField()),
                ('original_word_count', models.PositiveIntegerField(default=0)),
                ('summary_word_count', models.PositiveIntegerField(default=0)),
                ('compression_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
